#!/usr/bin/env bash
# Tell story of Passwd
file=/etc/passwd

# set the Internal Field Separator to |
IFS=':'
while read -r USERNAME PASSWORD GROUPID ONE TWO HOMEDIRECTORY COMMAND
do
        printf "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIRECTORY and rides $COMMAND. $GROUPID's place is protected by the passcode $PASSWORD, more info about the user here: $USERNAME\n"
	
done < "$file"
