#!/usr/bin/env bash
# Tell story of Passwd
file=/etc/passwd

# set the Internal Field Separator to |
IFS=':'
while read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOMEDIRECTORY COMMANDSHELL
do
        echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIRECTORY and rides $COMMANDSHELL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
	
done < "$file"
