#!/usr/bin/env bash
# While Loop 10 Times

nbr=0
while ((nbr < 8))
do
        echo "Best School"
        ((nbr++))
if [[ $nbr == 3 ]]; then
    echo "bad luck"
elif [[ $nbr == 6 ]];then
    echo "good luck"
else
continue
  fi
done
