#!/usr/bin/env bash
# While Loop 10 Times

i=0
while [ $i -le 7 ]
do
    echo "Best School"
  ((i++))
  if [[ $i == 3 ]];then
    echo "bad luck"
  elif [[ $i == 6 ]];then
    echo "good luck"
  fi
done
