#!/usr/bin/env bash
# While Loop 20 Time with condition ( with case )
i=1
while ((i <= 20))
do
    echo $i
  ((i++))
 case $i in
 5)
 echo "bad luck from China"
 ;;
 10)
 echo "bad luck from Japan"
 ;;
 18)
 echo "bad luck from Italy"
esac
done
