#!/usr/bin/env bash
# While Loop with case and condition
nbrhour=1
nbr=1
echo "Hour: 0"
while ((nbrhour <= 12))
do
        echo $nbr
        ((nbr++))
case $nbr in
 60)
 nbr=1
 echo "Hour: $nbrhour"
 ((nbrhour++))
 ;;
esac
done
while ((nbr < 60))
do
	echo $nbr
	((nbr++))
done
