#!/usr/bin/env bash
# 

rmfile()
{
	sudo rm -f /var/run/myscript.pid;
	exit
}

sudo bash -c "echo $$ > /var/run/myscript.pid"

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile" SIGTERM
trap "echo 'I hate the kill command'; rmfile" SIGQUIT

while(true)
do
	echo "To infinity and beyond"
	sleep 2
done
