#!/usr/bin/env bash
# 

rmfile()
{
	rm -f /var/run/myscript.pid;
	exit
}

echo $$ > /var/run/myscript.pid

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile" SIGTERM
trap "echo 'I hate the kill command'; rmfile" SIGQUIT

while(true)
do
	echo "To infinity and beyond"
	sleep 2
done
