#!/usr/bin/env bash
#
startprog()
{
    ./manage_my_process & echo "$!" > /var/run/my_process.pid
}
stopprog()
{
    pkill -f ./manage_my_process
    sudo rm -f /var/run/my_process.pid
}
case "$1" in
    start) startprog
	   printf "manage_my_process started\n"
	   ;;
    stop) stopprog
	  printf "manage_my_process stopped\n"
	  ;;
    restart) stopprog
	     startprog
             printf "manage_my_process restarted\n"
	     ;;
    *) printf "Usage: manage_my_process {start|stop|restart}\n"
       ;;
esac
exit 0
