#!/usr/bin/env bash
#
startprog()
{
    ./manage_my_process & echo "$!" > /var/run/my_process.pid
}
stopprog()
{
    pkill -f ./manage_my_process
    sudo rm -f /var/run/my_process.pid
}
case "$1" in
    start) startprog
	   echo "manage_my_process started"
	   ;;
    stop) stopprog
	  echo "manage_my_process stopped"
	  ;;
    restart) stopme
	     startme
             echo "manage_my_process restarted"
	     ;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
       ;;
esac
exit 0
